In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as s
import numpy as n

In [15]:
data =pd.read_csv('C:/Users/Surya/OneDrive/Desktop/pro/data/heart.csv')

In [16]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52  1.0   0       125   212    0        1      168      0      1.0   
1      53  1.0   0       140   203    1        0      155      1      3.1   
2      70  NaN   0       145   174    0        1      125      1      2.6   
3      61  1.0   0       148   203    0        1      161      0      0.0   
4      62  0.0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59  1.0   1       140   221    0        1      164      1      0.0   
1021   60  1.0   0       125   258    0        0      141      1      2.8   
1022   47  1.0   0       110   275    0        0      118      1      1.0   
1023   50  0.0   0       110   254    0        0      159      0      0.0   
1024   54  1.0   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [17]:
df = data.dropna()

In [18]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [19]:
#preprocessing, split test and dataset, split response variable
X = df.drop(labels='target', axis=1)
#Response variable
y = df.loc[:,'target'] 

In [20]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52  1.0   0       125   212    0        1      168      0      1.0   
1      53  1.0   0       140   203    1        0      155      1      3.1   
3      61  1.0   0       148   203    0        1      161      0      0.0   
4      62  0.0   0       138   294    1        1      106      0      1.9   
5      58  0.0   0       100   248    0        0      122      0      1.0   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59  1.0   1       140   221    0        1      164      1      0.0   
1021   60  1.0   0       125   258    0        0      141      1      2.8   
1022   47  1.0   0       110   275    0        0      118      1      1.0   
1023   50  0.0   0       110   254    0        0      159      0      0.0   
1024   54  1.0   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
3         2   1     3  
4         1   3     2  
5         1   0     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1024 rows x 13 columns]

In [21]:
y

0       0
1       0
3       0
4       0
5       1
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1024, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1, stratify=y)

In [24]:
print("Number of training dataset: ", len(X_train))
print("Number of test dataset: ", len(X_test))
print("Total number of dataset: ", len(X_train)+len(X_test))

Number of training dataset:  716
Number of test dataset:  308
Total number of dataset:  1024


In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
dtree=  DecisionTreeClassifier()

In [27]:
dtree.fit(X_train,y_train)


DecisionTreeClassifier()

In [28]:
predictDT = dtree.predict(X_test)

In [29]:
predictDT 

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,

In [30]:
y_test

35     0
740    1
562    1
534    1
445    1
      ..
574    0
543    0
595    0
147    0
41     1
Name: target, Length: 308, dtype: int64

In [31]:
#According to the cross-validated MCC scores, the random forest is the best-performing model, so now let's evaluate its performance on the test set.
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [32]:
conf_ma=confusion_matrix(y_test,predictDT)
print('Confusion Matrix result of Random Forest Algorithm is:\n',conf_ma)
print(conf_ma)

Confusion Matrix result of Random Forest Algorithm is:
 [[146   4]
 [  0 158]]
[[146   4]
 [  0 158]]


In [33]:
cla_report=classification_report(y_test,predictDT)
print("classification report of Random Forest Algortithm Results:")
print(cla_report)

classification report of Random Forest Algortithm Results:
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       150
           1       0.98      1.00      0.99       158

    accuracy                           0.99       308
   macro avg       0.99      0.99      0.99       308
weighted avg       0.99      0.99      0.99       308



In [34]:
acc=accuracy_score(y_test,predictDT)
print("accuracy score of DT:",acc*100)

accuracy score of DT: 98.7012987012987
